#define TEXT_KEYBOARD			L"Keyboard Config"
#define TEXT_MOUSE				L"Mouse Config"
#define TEXT_ABOUT				L"Info..."
#define TEXT_EXIT				L"E&xit"
#define TEXT_CONFIG				"&Config"
#define TEXT_WC3ISK_ON			"Wc3isk is On"
#define TEXT_WC3ISK_OFF			"Wc3isk is Off"
#define TEXT_KBHKOFF			"Toggle ON/OFF:"
#define KEYSETFILE				L"setting.dat"
#define TEXT_LOADED_ALERT		L"Wc3isk has been loaded!"
#define TEXT_WC3_CLASSNAME		L"Warcraft III"
#define TEXT_ABOUT_LINK			L"http://ceezblog.info/wc3isk"
#define TEXT_ABOUT_HOMEPAGE		L"Wc3isk Homepage"
#define TEXT_PRESS_A_KEY		"Assign new key"
#define TEXT_ASSIGN_ERROR		"That key is not allowed"

#define TEXT_TITLE				"WC3ISK v2.1 RC6"
#define TEXT_ABOUT_LONG			L"Warcraft III - Inventory Short Key v2.1 rc6 is a \r\nhot-key tool for Warcraft III, especially for DoTA.\r\n\r\nBy Kemsusu (aka 1413, aka Cee'z) © 2007 - 2011\r\nEmail: vuhchuong@gmail.com\r\n\r\nI changed many things since the last version.\r\nVisit http://ceezblog.info/wc3isk\r\nor following the Hyperlink below."
#define TEXT_APPNAME_PLATFORM	L"Wc3isk v2.1 RC6 - Windows 7 (x86)\r\nRelease date: Mar 15th 2011"
